cc_library(
    name = "world",
    srcs = [
    ],
    hdrs = [    
        "world/world.h",        
    ],
    deps = [

    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "agent",
    srcs = [
    ],
    hdrs = [    
        "agent/agent.h",        
    ],
    deps = [

    ],
    visibility = ["//visibility:public"],
)
