cc_library(
    name = "world",
    srcs = glob(["world/*.cpp"]),
    hdrs = glob(["world/*.h"]),
    deps = [

    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "commons",
    srcs = glob(["commons/*.cpp"]),
    hdrs = glob(["commons/*.h"]),
    deps = [

    ],
    visibility = ["//visibility:public"],
)

