cc_test(
    name = "observer_tests",
    srcs = [
        "observer_tests.cpp",
    ],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "//src/environment:world",
        "//src/environment:commons",
        "@gtest//:main",
    ],
)

cc_test(
    name = "geometry_tests",
    srcs = [
        "geometry_tests.cpp",
    ],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "//src/environment:world",
        "//src/environment:commons",
        "@gtest//:main",
    ],
)

cc_test(
    name = "kinematics_tests",
    srcs = [
        "kinematics_tests.cpp",
    ],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "//src/environment:world",
        "//src/environment:commons",
        "@gtest//:main",
    ],
)
