package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # Apache 2.0

load(
  "@io_bazel_rules_python//python:python.bzl",
  "py_binary", "py_library", "py_test",
)

load("@my_deps//:requirements.bzl", "requirement")

py_binary(
    name = "simulation",
    srcs = ["simulation.py"],
    deps = [
    ],
)