cc_proto_library(
    name = "object_cc_proto",
    deps = [":object_proto"],
	visibility = ["//visibility:public"]
)

proto_library(
    name = "object_proto",
    srcs = ["object.proto"],
    deps = [":commons_proto"],
)

proto_library(
    name = "commons_proto",
    srcs = ["commons.proto"],
    deps = [],
)
